'use client'
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { cn } from "@/lib/utils"
import Script from "next/script";
import "./globals.css";
import { useEffect } from "react";

const poppins = Poppins({ 
  subsets: ["latin", "latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  preload: true,
});


 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  useEffect(() => {
  
    window.googleTranslateElementInit = () => {
     new window.google.translate.TranslateElement({ pageLanguage: 'en' }, 'google_translate_element');
    };
  
   }, []);
  return (
    <html lang="en">
      <head>
    
    {/* Google Translate */}
    {/* <Script
     src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
    ></Script> */}

    {/* Google Translate CSS */}
    {/* <link
     rel="stylesheet"
     type="text/css"
     href="https://www.gstatic.com/_/translate_http/_/ss/k=translate_http.tr.26tY-h6gH9w.L.W.O/am=CAM/d=0/rs=AN8SPfpIXxhebB2A47D9J-MACsXmFF6Vew/m=el_main_css"
    /> */}

   </head>
      {/* <body className={ poppins.className}> */}
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          poppins.className
        )}>
          <div id="google_translate_element" style={{ position: 'fixed', right: 0, bottom: 0, zIndex: 1000, backgroundColor:'rgba(255, 255, 255, 0.7)', borderRadius:'10px', padding:'5px' }}></div>
        {children}
      </body>
    </html>
  );
}
